name: compression
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
